import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { createCancelProfileConsultation } from "../../src/fsd/features/cancel-consultation/model/createCancelProfileConsultation.ts";

const calls: Array<[string, number]> = [];
const cancel = createCancelProfileConsultation(async (kind, id) => {
  calls.push([kind, id]);
  return "ok";
});
await cancel(9);
assert.deepEqual(calls, [["common", 4]]);

const read = (path: string) => readFileSync(resolve(process.cwd(), path), "utf8");
const route = read("app/profile/page.tsx");
const page = read("src/fsd/pages/profile/ui/ProfilePage.tsx");
const api = read("src/fsd/pages/profile/api/profile.ts");
const entityProfilePath = "src/fsd/entities/user/api/profile.ts";
const entityProfile = existsSync(entityProfilePath) ? read(entityProfilePath) : "";
const userIndex = read("src/fsd/entities/user/index.ts");
const profileHook = read("src/fsd/pages/profile/model/useProfilePage.ts");
const avatarFeatureApiPath = "src/fsd/features/change-profile-avatar/api/uploadProfileAvatar.ts";
const avatarFeatureHookPath = "src/fsd/features/change-profile-avatar/model/useChangeProfileAvatar.ts";
const avatarFeatureApi = existsSync(avatarFeatureApiPath) ? read(avatarFeatureApiPath) : "";
const avatarFeatureHook = existsSync(avatarFeatureHookPath) ? read(avatarFeatureHookPath) : "";
const widget = read("src/fsd/widgets/profile-consultations/ui/ProfileConsultations.tsx");

assert.match(route, /@fsd\/pages\/profile/);
assert.match(page, /StudentHeader/);
assert.match(page, /useProfilePage/);
assert.doesNotMatch(page, /fetchUserProfile|cancelProfileConsultation/);
assert.match(api, /getUpcoming/);
assert.doesNotMatch(api, /getAll/);
assert.match(api, /getSession/);
assert.match(api, /session\?\.role === "TEACHER"/);
assert.match(api, /upcomingCourse: \[\]/);
assert.match(api, /getUserProfile/);
assert.doesNotMatch(api, /requestWithSession<[^>]+>\("\/auth\/profile"\)/);
assert.match(avatarFeatureApi, /requestWithSession[\s\S]{0,180}"\/auth\/profile\/image"/);
assert.match(avatarFeatureApi, /new FormData\(\)/);
assert.match(avatarFeatureApi, /formData\.append\("image", file\)/);
assert.match(avatarFeatureApi, /"\/auth\/profile\/image",[\s\S]*\{ method: "PATCH"/);
assert.doesNotMatch(avatarFeatureApi, /"\/auth\/profile\/image",[\s\S]*\{ method: "POST"/);
assert.match(profileHook, /useChangeProfileAvatar/);
assert.doesNotMatch(profileHook, /uploadProfileImage/);
assert.doesNotMatch(api, /uploadProfileImage/);
assert.doesNotMatch(api, /new FormData\(\)/);
assert.match(avatarFeatureApi, /"\/auth\/profile\/image"/);
assert.match(avatarFeatureApi, /method: "PATCH"/);
assert.match(avatarFeatureHook, /useChangeProfileAvatar/);
assert.match(api, /profileImageUrl/);
assert.match(api, /resolveProfileImageUrl/);
assert.match(userIndex, /getUserProfile/);
assert.match(userIndex, /resolveProfileImageUrl/);
assert.match(entityProfile, /requestWithSession<[^>]+>\("\/auth\/profile"\)/);
assert.match(entityProfile, /resolveProfileImageUrl/);
assert.match(widget, /예약 현황/);
assert.match(widget, /예약 취소/);
assert.match(page, /studentId|학번/);
assert.doesNotMatch(page, /학번\s*\{/);
assert.doesNotMatch(widget, /상담 기록|myMemo|TextAreaField/);

console.log("profile fsd page contract passed");
